### ISSUE TITLE
doubts about how to use connection with fingerprint

### ISSUE THREAD

**Issue by droidprova** [cotestatnt/CTBot#17]
Hi,
congratulations for your library, I find it much lighter than the others, and it was easy to use it and communicate with my bot. I have some questions for you about using the finger print:

1. if I declare this in setup ():

// Set the Telegram bot properies
  // api.telegram.org
  uint8_t telegramFingerprint [20] = { 0xBB, 0xDC, 0x45, 0x2A, 0x07, 0xE3, 0x4A, 0x71, 0x33, 0x40, 0x32, 0xDA, 0xBE, 0x81, 0xF7, 0x72, 0x6F, 0x4A, 0x2B, 0x6B }; // https://www.grc.com/fingerprints.htm
  myBot.setFingerprint(telegramFingerprint);
  myBot.updateFingerPrint();
  myBot.setUpdateTime(2000);
  myBot.setTelegramToken(token);
  myBot.begin();

is my connection with the telegram server already encrypted or do I have to do something else?

2. how myBot.updateFingerPrint () works from the documentation I can't understand. Do you have any examples?

Thank you

**Comment by cotestatnt** [comment]
Hi!
The method _updateFingerPrint()_ try to parse this address [https://www.grc.com/fingerprints.htm?chain=api.telegram.org](url) in order to get updated fingerprint for Telegram host (fingerprint will change yearly more or less). 
I would suggest to you, to call method only if connection with Telegram server fails (myBot.begin() == false).

Anyway, for next major release, I'm planning to ditch the fingerprint method and use the full trusted root certificates wich is well handled both ESP32 WiFiClientSecure and from ESP8266 BearSSL library.

You can find it in dev branch, but it's still buggy.

**Comment by droidprova** [comment]
Grazie mille

**Comment by droidprova** [comment]
it happens that I use your library in a Sketch with the wifi-manager library I have many reboots. Do you agree?

**Comment by cotestatnt** [comment]
> it happens that I use your library in a Sketch with the wifi-manager library I have many reboots. Do you agree?

No, this it's new for me. Can you reproduce or provide more information about the issue?
I've just tried on one of my esp32 the "keyboard.ino" example  with the library WiFi Manager and work as expected.
