### ISSUE TITLE
How to get the user chat_id

### ISSUE THREAD

**Issue by spyfox147** [cotestatnt/CTBot#38]
i'm trying to make some kind of user authentication and the only possible way to track a user is by chat id, but i couldn't see any public method or attribute in the header file referring to the chat id for an incoming message, is it not possible or i didn't notice it ?

**Comment by cotestatnt** [comment]
I'm not sure I've understood what you want to do in your application.
However the id of the user who sends the message (in reality it is the id of the chat, but it is equivalent), you can get for example in this way:
`uint32_t userid = msg.sender.id`

Or if you need to know it before compiling by sending a message to the bot [https://t.me/JsonDumpBot](https://t.me/JsonDumpBot)

Unfortunately there is no way to figure it out from the username like _@my_username_ (or at least I'm not aware of it)

**Comment by spyfox147** [comment]
thank you, what i was trying to do is to store a list of IDs in eeprom  for the authentication of who can get response from my bot.
i also was wondering if the library has timeout for checking NTP server, if there's no internet connection it will keep checking forever

**Comment by gnalbandian** [comment]
Hi @cotestatnt , @spyfox147.

@spyfox147 I get what you need. In fact I've done it in my fork of the repo (not online) which unfortunately, has grown very much apart from this one in which it is based upon.
Maybe if you are interested I could take some time to make it available online.
I have get rid of all String variables.
It has some new features and protection mechanisms.
I believe it's a little bit faster and light but haven't prove it.

PD: It's only for esp8266 because I haven't got an esp32 and that makes it hard to debug.

**Comment by spyfox147** [comment]
@gnalbandian  i started working adding support for timeout and auto reconnect the NTP server  because when there's no internet connection it will keep delaying forever waiting NTP, so when it timeout the esp will continue working and will check NTP server later. i wonder if your fork support that

**Comment by cotestatnt** [comment]
> i also was wondering if the library has timeout for checking NTP server, if there's no internet connection it will keep checking forever
@spyfox147 you should sync clock with NTP server only when internet connection is active. 
Anyway, it's quite simple add a timeout checking [(check commit)](https://github.com/cotestatnt/AsyncTelegram/commit/c4d9e4397b1ef0d007a2b7abcc95bd7ae9bd5098)

```
if (WiFi.connected())){
   myBot.setClock("CET-1CEST,M3.5.0,M10.5.0/3", 10000);
}
```

I haven't developed so much functionality around system clock because is strictly platfrom dependent, and i'm going to a different path with AsyncTelegram2 (platform and transport independency).

**Comment by gnalbandian** [comment]
I have left all ntp-related stuff out of the library as I believe that it doesn't belong inside it. Just a philosophy matter. 
I deal with it outside the library.

**Comment by cotestatnt** [comment]
> I believe that it doesn't belong inside it

I agree. This is why I changed my mind and removed the feature in the new version.
