### ISSUE TITLE
connection status checking and stop

### ISSUE THREAD

**Issue by jssahoo** [cotestatnt/CTBot#43]
How to check connection status other than begin() and how to stop connection to telegram ?

**Comment by cotestatnt** [comment]
Hi @jssahoo
In order to check connection with Telegram server you can simply call this method for at least "telegram minimum update" interval (default 2 seconds).
` bool getUpdates();`
If you get **true** in this time window, connection is ok.

To stop connection, simply avoid to call the **getNewMessage()** method
