### ISSUE TITLE
Transmitting characters

### ISSUE THREAD

**Issue by Grs2002** [cotestatnt/CTBot#45]
hello! A good library! The only question is, if you load the sketch from the echo example, the transmission of the characters -,*,. does not work, and if you write any other character, for example, 567, everything works. I use esp8266 nodemcu, board version 2.7.4, json 6.18.0. Sorry for my English))

**Comment by cotestatnt** [comment]
Hellp @Grs2002 

Sorry for late response, but actually i'm not developing anymore this repo because i'm working on the new **major** [version 2](https://github.com/cotestatnt/AsyncTelegram2).
I invite you to try it because there are many improvements and it is more reliable; for example I've just tested this issue and all special and also accented characters are supported.

At the moment it is not yet in the library manager of the Arduino IDE, you have to donwload zip file.

**Comment by Grs2002** [comment]
thanks for the answer! I tried version 2, really works, characters are passed, but esp8266 nodmcu 4mb reboots itself sometimes, can't solve this problem yet

**Comment by fmarzocca** [comment]
move this to AsyncTelegram2

**Comment by cotestatnt** [comment]
Yes, please @Grs2002 open this issue in the version 2 repository.
Could you add also some more detailed information in order to be able to reproduce a similar condition from my side?
